# Generated by Django 4.2.4 on 2023-10-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialdata',
            old_name='timestamp',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='financialdata',
            name='timeframe',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
